spring.application.name=blog-api
spring.datasource.url=jdbc:mysql://localhost:3306/blogdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Shourya@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT properties (we will use these later)
jwt.secret=WmQo2W36pmnTVsLsfhtv4TGenx4kFGrCePHqdJ86uqVyJ/iZbry/3sJ+fHpI2bZblNYpBeitFW7U/NlH3nwFoA==

jwt.expiration=3600000  
